import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/index/Footer";
import Header from "@/components/index/Header";
import { ThemeProvider } from "@/components/theme-provider";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased flex flex-col min-h-screen relative`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem> 
          <div className="relative">
            <Header />
            <main className="relative">{children}</main> 
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
